### ISSUE TITLE
patch of tensorflow/opencv

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/jetson_nano#10]
Hi,
What's these patch files? why you use these patch? If I want to insatll tensorflow-15 on jetpack 4.4, Is it compatibile with this version?

**Comment by jkjung-avt** [comment]
The OpenCV patch file is needed.  Otherwise the build process fails (compilation errors) on Jetson Nano/TX2.

On the other hand, I created the TensorfFlow patch files by referencing others' experiences in building TensorFlow on Jetson platforms.

JetPack-4.4 is using cuDNN 8.  TensorFlow-1.15 source code (natively working for cuDNN 7) would need to be modified quite a bit in order to build with it.  I haven't managed to get it to work so far.

**Comment by PythonImageDeveloper** [comment]
In the tensorflow patch, you modified a quite a bit for only cuDNN compability? I want to know if you did same work, I also did same work for cuDNN 8.
If you have some references about such work, please liked here, even likes of building Tensorflow -1.15 with CuDNN 7

**Comment by jkjung-avt** [comment]
Patch of tensorflow-1.15.0 with cuDNN 7 is in this repository already: https://github.com/jkjung-avt/jetson_nano/blob/master/tensorflow/tensorflow-1.15.0.patch

As I already stated, I haven't done it for cuDNN 8.

**Comment by PythonImageDeveloper** [comment]
Thanks,
What's main diffrence between tensorflow package released of nvidia and your build tensorflow package from source?
If I use pre-build of nvidia package, maybe I faced with some error in the converting to tensorrt?

**Comment by jkjung-avt** [comment]
I don't know.  I only make sure the tensorflow package I built supports the correct version of CUDA, cuDNN and TensorRT.
