### ISSUE TITLE
build whl tensorflow 1.12 and not tensorflow-gpu-1.12

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/jetson_nano#5]
Hi
when I build the TensorFlow 1.12 from source with your script, after the building whl finished, created TensorFlow-1.12.2-cp36-cp36m-linux_aarch64.whl, and after the package installed and I run pip3 freeze, the terminal shows me tensorflow==1.12.2 and the before installed package TensorFlow-gpu==1.14.0+nv19.10 is also show me, why? are your scripts build the TensorFlow on CPU mode or GPU?

**Comment by jkjung-avt** [comment]
I think this is because the NVIDIA tensorflow package is named "tensorflow-gpu" and was not removed by `sudo pip3 uninstall tensorflow`.  You could check your installed python packages/modules by `sudo pip3 list | grep tensorflow`.

The fix should be simple.  Just do `sudo pip3 uninstall tensorflow-gpu` to remove the package which you no longer need.
